# Generated by Django 4.2.2 on 2023-06-25 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LockedAmount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, editable=False, max_digits=14, verbose_name='Amount')),
                ('unlock_at', models.DateTimeField(verbose_name='Unlock at')),
                ('wallet', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='locked_amounts', to='wallet.wallet', verbose_name='Wallet')),
            ],
            options={
                'verbose_name': 'Locked Amount',
                'verbose_name_plural': 'Locked Amounts',
            },
        ),
    ]
