# Generated by Django 4.2.2 on 2023-06-25 23:07

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_lockedamount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lockedamount',
            name='amount',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Amount'),
        ),
    ]
