# Generated by Django 4.2.2 on 2023-06-25 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_alter_lockedamount_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lockedamount',
            name='amount',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=14, verbose_name='Amount'),
        ),
    ]
