# Generated by Django 4.2.2 on 2023-06-26 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0005_transaction_available_at_delete_lockedamount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['created_at'], 'verbose_name': 'Transaction', 'verbose_name_plural': 'Transactions'},
        ),
    ]
